#!/bin/sh
. ~/.config/hyprv.conf

#set the xfce and GTK theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"

#change the background image and be cool about it ;)
if [ -z $SET_BG ]; then
    swww img ~/.config/backgrounds/v4'-background-dark'.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
else
    swww img $SET_BG --transition-fps 60 --transition-type wipe --transition-duration 2
fi

#update the sddm image
cp -f ~/.config/backgrounds/$VER'-background'$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg
